---
- name: vscl to vpc conf
  hosts: all
  become: yes

  tasks:
  - name: Print OS info
    debug: var={{ item }}
    loop:
      - ansible_distribution
      - ansible_distribution_release
      - ansible_os_family
      - ansible_lsb
      - ansible_distribution_major_version


  - name: add include to network config
    lineinfile:
      path: /etc/network/interfaces
      state: present
      line: source /etc/network/interfaces.d/*.cfg
    check_mode: yes
    register: check_source_in_interfaces_conf
  
  - name: add block include to network config
    blockinfile:
      path: /etc/network/interfaces
      state: present
      marker: ""
      insertafter: EOF
      block: |
        source /etc/network/interfaces.d/*.cfg
    when: check_source_in_interfaces_conf.changed == true