---
- name: vscl to vpc conf
  hosts: all

  roles:
    - { role: ubuntu_16.04, when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial' }
    - { role: centos_7, when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7' }
    - { role: debian_9, when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch' }
    - { role: ubuntu_18.04, when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic' }
    - { role: ubuntu_14.04, when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'trusty' }
