---
# tasks file for debian_9
- name: Add signing key
  apt_key:
    url: http://repo.os.selectel.org/selectel-openstack.key
    state: present

- apt_repository:
    repo: deb http://repo.vscale.io/ stretch main
    state: absent

- apt_repository:
    repo: deb http://repo.os.selectel.org stretch main
    state: present
    update_cache: yes

- name: disable services
  systemd: 
    name: "{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: yes
  loop:
    - scarlet-init-early.service
    - scarlet-init.service
  ignore_errors: yes

- name: Wait for dpkg unlock
  shell: "while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;"

- name: Uninstall scarlet-init
  apt: 
    name: scarlet-init
    state: absent
    autoremove: yes
    purge: yes

- name: del scarlet folders
  file: 
    path: "{{ item }}" 
    state: absent
  with_items:
    - /var/log/scarlet-init/
    - /var/lib/scarlet-init/
    - /etc/init/scarlet-init.override
    - /etc/init/scarlet-init-early.override
        
- name: Install cloud-init
  apt: 
    name: "{{ item }}"
    state: present
    force: yes
    #allow_unauthenticated: yes
    install_recommends: yes
  with_items:
    - set-root-pw
    - fstrim-blocks
    - crontab-randomizer
    - qemu-guest-agent
    - cloud-init
    - net-tools

- name: copy Debian_9 config files
  copy:
    src: "{{ item }}"
    dest: "{{ dst_cloud_cfg }}"
  with_items:
    - '05_logging.cfg'
    - '10_no_default_users.cfg'
    - '99_enable_ec2.cfg'
    - '99_first_boot_routines.cfg'
    - '99_keep_root_user.cfg'
    - '99_location.cfg'
    - '99_selectel_mirror.cfg'
    - '99_ssh_settings.cfg'

- name: Service cloud-init start
  service: 
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - qemu-guest-agent
    - cloud-init
    - cloud-init-local
    - cloud-config
    - cloud-final
  #notify: Restart server

# - name: copy Grub config files
#   copy:
#     src: "grub_ubuntu.txt"
#     dest: "/etc/default/grub"
#     force: yes
#   notify: "Write grub"